name: Run Tests and Save Report

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
      JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Prepare environment
        run: |
          cp .env.example .env
          sed -i 's|JIRA_EMAIL=|JIRA_EMAIL=${{ secrets.JIRA_EMAIL }}|' .env
          sed -i 's|JIRA_PASSWORD=|JIRA_PASSWORD=${{ secrets.JIRA_PASSWORD }}|' .env
          sed -i 's|JIRA_USERNAME=|JIRA_USERNAME=${{ secrets.JIRA_USERNAME }}|' .env
          sed -i 's|JIRA_API_TOKEN=|JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }}|' .env
          sed -i 's|LEAD_ACCOUNT_ID=|LEAD_ACCOUNT_ID=${{ secrets.LEAD_ACCOUNT_ID }}|' .env
          sed -i 's|HEADLESS=|HEADLESS=true|' .env

      - name: Install dependencies & Playwright Browsers
        run: |
          npm install
          npx playwright install

      - name: Run tests
        run: npm test

      - name: Archive Screenshots if failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/*.png

      - name: Archive HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: reports/cucumber-report.html
